// flow-typed signature: 1fc6be4f0f8fe1b550bb9f2be8ed503f
// flow-typed version: <<STUB>>/bootstrap-styl_v^5.0.8/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-styl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-styl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-styl/Gruntfile' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/affix' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/alert' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/button' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/modal' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/popover' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/tab' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap-styl/js/transition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-styl/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap-styl/Gruntfile'>;
}
declare module 'bootstrap-styl/index' {
  declare module.exports: $Exports<'bootstrap-styl'>;
}
declare module 'bootstrap-styl/index.js' {
  declare module.exports: $Exports<'bootstrap-styl'>;
}
declare module 'bootstrap-styl/js/affix.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/affix'>;
}
declare module 'bootstrap-styl/js/alert.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/alert'>;
}
declare module 'bootstrap-styl/js/button.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/button'>;
}
declare module 'bootstrap-styl/js/carousel.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/carousel'>;
}
declare module 'bootstrap-styl/js/collapse.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/collapse'>;
}
declare module 'bootstrap-styl/js/dropdown.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/dropdown'>;
}
declare module 'bootstrap-styl/js/modal.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/modal'>;
}
declare module 'bootstrap-styl/js/popover.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/popover'>;
}
declare module 'bootstrap-styl/js/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/scrollspy'>;
}
declare module 'bootstrap-styl/js/tab.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/tab'>;
}
declare module 'bootstrap-styl/js/tooltip.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/tooltip'>;
}
declare module 'bootstrap-styl/js/transition.js' {
  declare module.exports: $Exports<'bootstrap-styl/js/transition'>;
}
