// flow-typed signature: 52d14f8a1a3c7f497387b26480714ab0
// flow-typed version: <<STUB>>/brunch_v^2.8.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brunch/lib/cli' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/asset' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/file_list' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/generate' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/is_ignored' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/pipeline' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/source_file' {
  declare module.exports: any;
}

declare module 'brunch/lib/fs_utils/write' {
  declare module.exports: any;
}

declare module 'brunch/lib/index' {
  declare module.exports: any;
}

declare module 'brunch/lib/run-cli' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/config-validate' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/config' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/error' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/helpers' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/hmr' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/modules' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/plugin-adapter' {
  declare module.exports: any;
}

declare module 'brunch/lib/utils/plugins' {
  declare module.exports: any;
}

declare module 'brunch/lib/watch' {
  declare module.exports: any;
}

declare module 'brunch/lib/workers/index' {
  declare module.exports: any;
}

declare module 'brunch/lib/workers/job-processor' {
  declare module.exports: any;
}

declare module 'brunch/lib/workers/manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brunch/lib/cli.js' {
  declare module.exports: $Exports<'brunch/lib/cli'>;
}
declare module 'brunch/lib/fs_utils/asset.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/asset'>;
}
declare module 'brunch/lib/fs_utils/file_list.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/file_list'>;
}
declare module 'brunch/lib/fs_utils/generate.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/generate'>;
}
declare module 'brunch/lib/fs_utils/is_ignored.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/is_ignored'>;
}
declare module 'brunch/lib/fs_utils/pipeline.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/pipeline'>;
}
declare module 'brunch/lib/fs_utils/source_file.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/source_file'>;
}
declare module 'brunch/lib/fs_utils/write.js' {
  declare module.exports: $Exports<'brunch/lib/fs_utils/write'>;
}
declare module 'brunch/lib/index.js' {
  declare module.exports: $Exports<'brunch/lib/index'>;
}
declare module 'brunch/lib/run-cli.js' {
  declare module.exports: $Exports<'brunch/lib/run-cli'>;
}
declare module 'brunch/lib/utils/config-validate.js' {
  declare module.exports: $Exports<'brunch/lib/utils/config-validate'>;
}
declare module 'brunch/lib/utils/config.js' {
  declare module.exports: $Exports<'brunch/lib/utils/config'>;
}
declare module 'brunch/lib/utils/error.js' {
  declare module.exports: $Exports<'brunch/lib/utils/error'>;
}
declare module 'brunch/lib/utils/helpers.js' {
  declare module.exports: $Exports<'brunch/lib/utils/helpers'>;
}
declare module 'brunch/lib/utils/hmr.js' {
  declare module.exports: $Exports<'brunch/lib/utils/hmr'>;
}
declare module 'brunch/lib/utils/modules.js' {
  declare module.exports: $Exports<'brunch/lib/utils/modules'>;
}
declare module 'brunch/lib/utils/plugin-adapter.js' {
  declare module.exports: $Exports<'brunch/lib/utils/plugin-adapter'>;
}
declare module 'brunch/lib/utils/plugins.js' {
  declare module.exports: $Exports<'brunch/lib/utils/plugins'>;
}
declare module 'brunch/lib/watch.js' {
  declare module.exports: $Exports<'brunch/lib/watch'>;
}
declare module 'brunch/lib/workers/index.js' {
  declare module.exports: $Exports<'brunch/lib/workers/index'>;
}
declare module 'brunch/lib/workers/job-processor.js' {
  declare module.exports: $Exports<'brunch/lib/workers/job-processor'>;
}
declare module 'brunch/lib/workers/manager.js' {
  declare module.exports: $Exports<'brunch/lib/workers/manager'>;
}
