// flow-typed signature: d9ce0b73bc30d1bb04bb38efd3a6fbfd
// flow-typed version: <<STUB>>/eslint-brunch_v^3.11.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-brunch/index' {
  declare module.exports: $Exports<'eslint-brunch'>;
}
declare module 'eslint-brunch/index.js' {
  declare module.exports: $Exports<'eslint-brunch'>;
}
