// flow-typed signature: e00173dabc63b1c83c52a65cb5ad5f2b
// flow-typed version: <<STUB>>/eslint-brunch_v^3.12.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-brunch/index' {
  declare module.exports: $Exports<'eslint-brunch'>;
}
declare module 'eslint-brunch/index.js' {
  declare module.exports: $Exports<'eslint-brunch'>;
}
