// flow-typed signature: 1671494fc4d487fa577e5379fdd69409
// flow-typed version: <<STUB>>/fb-flo-brunch_v^1.7.22/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fb-flo-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fb-flo-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fb-flo-brunch/test/core' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fb-flo-brunch/index' {
  declare module.exports: $Exports<'fb-flo-brunch'>;
}
declare module 'fb-flo-brunch/index.js' {
  declare module.exports: $Exports<'fb-flo-brunch'>;
}
declare module 'fb-flo-brunch/test/core.js' {
  declare module.exports: $Exports<'fb-flo-brunch/test/core'>;
}
