// flow-typed signature: 2d9a0962bad4c39309ad7f3e36b02e88
// flow-typed version: <<STUB>>/stylus-brunch_v^2.10.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylus-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylus-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylus-brunch/fixtures/plugin-import-module/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylus-brunch/fixtures/plugin-import-module/index.js' {
  declare module.exports: $Exports<'stylus-brunch/fixtures/plugin-import-module/index'>;
}
declare module 'stylus-brunch/index' {
  declare module.exports: $Exports<'stylus-brunch'>;
}
declare module 'stylus-brunch/index.js' {
  declare module.exports: $Exports<'stylus-brunch'>;
}
